//
// Generated file, do not edit! Created by opp_msgtool 6.3 from models/MoqObjectChunk.msg.
//

#ifndef __MOQVEINSSIM_MOQOBJECTCHUNK_M_H
#define __MOQVEINSSIM_MOQOBJECTCHUNK_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace moqveinssim {

class MoqObjectChunk;

}  // namespace moqveinssim

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace moqveinssim {

/**
 * Class generated from <tt>models/MoqObjectChunk.msg:7</tt> by opp_msgtool.
 * <pre>
 * class MoqObjectChunk extends inet::FieldsChunk
 * {
 *     long trackId;
 *     string trackAlias;
 *     long groupId;
 *     long objectId;
 *     long priority;
 *     long payloadLength;
 *     simtime_t creationTime;
 * }
 * </pre>
 */
class MoqObjectChunk : public ::inet::FieldsChunk
{
  protected:
    long trackId = 0;
    ::omnetpp::opp_string trackAlias;
    long groupId = 0;
    long objectId = 0;
    long priority = 0;
    long payloadLength = 0;
    ::omnetpp::simtime_t creationTime = SIMTIME_ZERO;

  private:
    void copy(const MoqObjectChunk& other);

  protected:
    bool operator==(const MoqObjectChunk&) = delete;

  public:
    MoqObjectChunk();
    MoqObjectChunk(const MoqObjectChunk& other);
    virtual ~MoqObjectChunk();
    MoqObjectChunk& operator=(const MoqObjectChunk& other);
    virtual MoqObjectChunk *dup() const override {return new MoqObjectChunk(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual long getTrackId() const;
    virtual void setTrackId(long trackId);

    virtual const char * getTrackAlias() const;
    virtual void setTrackAlias(const char * trackAlias);

    virtual long getGroupId() const;
    virtual void setGroupId(long groupId);

    virtual long getObjectId() const;
    virtual void setObjectId(long objectId);

    virtual long getPriority() const;
    virtual void setPriority(long priority);

    virtual long getPayloadLength() const;
    virtual void setPayloadLength(long payloadLength);

    virtual ::omnetpp::simtime_t getCreationTime() const;
    virtual void setCreationTime(::omnetpp::simtime_t creationTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MoqObjectChunk& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MoqObjectChunk& obj) {obj.parsimUnpack(b);}


}  // namespace moqveinssim


namespace omnetpp {

template<> inline moqveinssim::MoqObjectChunk *fromAnyPtr(any_ptr ptr) { return check_and_cast<moqveinssim::MoqObjectChunk*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __MOQVEINSSIM_MOQOBJECTCHUNK_M_H

