//
// Generated file, do not edit! Created by opp_msgtool 6.3 from models/MoqObjectAck.msg.
//

#ifndef __MOQVEINSSIM_MOQOBJECTACK_M_H
#define __MOQVEINSSIM_MOQOBJECTACK_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace moqveinssim {

class MoqObjectAck;

}  // namespace moqveinssim

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace moqveinssim {

/**
 * Class generated from <tt>models/MoqObjectAck.msg:15</tt> by opp_msgtool.
 * <pre>
 * //
 * // Application-level acknowledgement sent by a subscriber to the relay once an
 * // object has been fully received and reassembled. The relay uses it to pace
 * // forwarding: the next object on a given (subscriber, track) stream is only
 * // sent after the previous object's ACK arrives. This guarantees the previous
 * // object is fully QUIC-ACKed (its stream send buffer is empty) before the next
 * // object is enqueued, so two objects never merge into a SequenceChunk.
 * //
 * class MoqObjectAck extends inet::FieldsChunk
 * {
 *     string subscriberId;
 *     string trackNamespace;
 *     string trackName;
 *     long objectId;
 * }
 * </pre>
 */
class MoqObjectAck : public ::inet::FieldsChunk
{
  protected:
    ::omnetpp::opp_string subscriberId;
    ::omnetpp::opp_string trackNamespace;
    ::omnetpp::opp_string trackName;
    long objectId = 0;

  private:
    void copy(const MoqObjectAck& other);

  protected:
    bool operator==(const MoqObjectAck&) = delete;

  public:
    MoqObjectAck();
    MoqObjectAck(const MoqObjectAck& other);
    virtual ~MoqObjectAck();
    MoqObjectAck& operator=(const MoqObjectAck& other);
    virtual MoqObjectAck *dup() const override {return new MoqObjectAck(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getSubscriberId() const;
    virtual void setSubscriberId(const char * subscriberId);

    virtual const char * getTrackNamespace() const;
    virtual void setTrackNamespace(const char * trackNamespace);

    virtual const char * getTrackName() const;
    virtual void setTrackName(const char * trackName);

    virtual long getObjectId() const;
    virtual void setObjectId(long objectId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MoqObjectAck& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MoqObjectAck& obj) {obj.parsimUnpack(b);}


}  // namespace moqveinssim


namespace omnetpp {

template<> inline moqveinssim::MoqObjectAck *fromAnyPtr(any_ptr ptr) { return check_and_cast<moqveinssim::MoqObjectAck*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __MOQVEINSSIM_MOQOBJECTACK_M_H

