//
// Generated file, do not edit! Created by opp_msgtool 6.3 from models/MoqPublisherAnnounce.msg.
//

#ifndef __MOQVEINSSIM_MOQPUBLISHERANNOUNCE_M_H
#define __MOQVEINSSIM_MOQPUBLISHERANNOUNCE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace moqveinssim {

class MoqPublisherAnnounce;

}  // namespace moqveinssim

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace moqveinssim {

/**
 * Class generated from <tt>models/MoqPublisherAnnounce.msg:7</tt> by opp_msgtool.
 * <pre>
 * class MoqPublisherAnnounce extends inet::FieldsChunk
 * {
 *     long publisherId;
 *     long trackId;
 *     string trackNamespace;
 *     string trackName;
 *     string trackAlias;
 *     string objectType;
 *     long payloadSize;
 *     simtime_t sendInterval;
 *     long priority;
 * }
 * </pre>
 */
class MoqPublisherAnnounce : public ::inet::FieldsChunk
{
  protected:
    long publisherId = 0;
    long trackId = 0;
    ::omnetpp::opp_string trackNamespace;
    ::omnetpp::opp_string trackName;
    ::omnetpp::opp_string trackAlias;
    ::omnetpp::opp_string objectType;
    long payloadSize = 0;
    ::omnetpp::simtime_t sendInterval = SIMTIME_ZERO;
    long priority = 0;

  private:
    void copy(const MoqPublisherAnnounce& other);

  protected:
    bool operator==(const MoqPublisherAnnounce&) = delete;

  public:
    MoqPublisherAnnounce();
    MoqPublisherAnnounce(const MoqPublisherAnnounce& other);
    virtual ~MoqPublisherAnnounce();
    MoqPublisherAnnounce& operator=(const MoqPublisherAnnounce& other);
    virtual MoqPublisherAnnounce *dup() const override {return new MoqPublisherAnnounce(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual long getPublisherId() const;
    virtual void setPublisherId(long publisherId);

    virtual long getTrackId() const;
    virtual void setTrackId(long trackId);

    virtual const char * getTrackNamespace() const;
    virtual void setTrackNamespace(const char * trackNamespace);

    virtual const char * getTrackName() const;
    virtual void setTrackName(const char * trackName);

    virtual const char * getTrackAlias() const;
    virtual void setTrackAlias(const char * trackAlias);

    virtual const char * getObjectType() const;
    virtual void setObjectType(const char * objectType);

    virtual long getPayloadSize() const;
    virtual void setPayloadSize(long payloadSize);

    virtual ::omnetpp::simtime_t getSendInterval() const;
    virtual void setSendInterval(::omnetpp::simtime_t sendInterval);

    virtual long getPriority() const;
    virtual void setPriority(long priority);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MoqPublisherAnnounce& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MoqPublisherAnnounce& obj) {obj.parsimUnpack(b);}


}  // namespace moqveinssim


namespace omnetpp {

template<> inline moqveinssim::MoqPublisherAnnounce *fromAnyPtr(any_ptr ptr) { return check_and_cast<moqveinssim::MoqPublisherAnnounce*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __MOQVEINSSIM_MOQPUBLISHERANNOUNCE_M_H

