//
// Generated file, do not edit! Created by opp_msgtool 6.3 from models/MoqSubscriber.msg.
//

#ifndef __MOQVEINSSIM_MOQSUBSCRIBER_M_H
#define __MOQVEINSSIM_MOQSUBSCRIBER_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace moqveinssim {

class MoqSubscriber;

}  // namespace moqveinssim

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace moqveinssim {

/**
 * Class generated from <tt>models/MoqSubscriber.msg:7</tt> by opp_msgtool.
 * <pre>
 * class MoqSubscriber extends inet::FieldsChunk
 * {
 *     string subscriberId;
 *     string trackNamespace;
 *     string trackName;
 *     long subscriberPriority;
 *     long startObjectId;
 * }
 * </pre>
 */
class MoqSubscriber : public ::inet::FieldsChunk
{
  protected:
    ::omnetpp::opp_string subscriberId;
    ::omnetpp::opp_string trackNamespace;
    ::omnetpp::opp_string trackName;
    long subscriberPriority = 0;
    long startObjectId = 0;

  private:
    void copy(const MoqSubscriber& other);

  protected:
    bool operator==(const MoqSubscriber&) = delete;

  public:
    MoqSubscriber();
    MoqSubscriber(const MoqSubscriber& other);
    virtual ~MoqSubscriber();
    MoqSubscriber& operator=(const MoqSubscriber& other);
    virtual MoqSubscriber *dup() const override {return new MoqSubscriber(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getSubscriberId() const;
    virtual void setSubscriberId(const char * subscriberId);

    virtual const char * getTrackNamespace() const;
    virtual void setTrackNamespace(const char * trackNamespace);

    virtual const char * getTrackName() const;
    virtual void setTrackName(const char * trackName);

    virtual long getSubscriberPriority() const;
    virtual void setSubscriberPriority(long subscriberPriority);

    virtual long getStartObjectId() const;
    virtual void setStartObjectId(long startObjectId);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MoqSubscriber& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MoqSubscriber& obj) {obj.parsimUnpack(b);}


}  // namespace moqveinssim


namespace omnetpp {

template<> inline moqveinssim::MoqSubscriber *fromAnyPtr(any_ptr ptr) { return check_and_cast<moqveinssim::MoqSubscriber*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __MOQVEINSSIM_MOQSUBSCRIBER_M_H

