//
// Generated file, do not edit! Created by opp_msgtool 6.3 from models/MoqTrackHeader.msg.
//

#ifndef __MOQVEINSSIM_MOQTRACKHEADER_M_H
#define __MOQVEINSSIM_MOQTRACKHEADER_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace moqveinssim {

class MoqTrackHeader;

}  // namespace moqveinssim

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace moqveinssim {

/**
 * Class generated from <tt>models/MoqTrackHeader.msg:7</tt> by opp_msgtool.
 * <pre>
 * class MoqTrackHeader extends inet::FieldsChunk
 * {
 *     long trackId;
 *     string trackName;
 *     long objectId;
 *     long payloadSize;
 *     simtime_t sendInterval;
 *     simtime_t creationTime;
 *     long priority;
 * }
 * </pre>
 */
class MoqTrackHeader : public ::inet::FieldsChunk
{
  protected:
    long trackId = 0;
    ::omnetpp::opp_string trackName;
    long objectId = 0;
    long payloadSize = 0;
    ::omnetpp::simtime_t sendInterval = SIMTIME_ZERO;
    ::omnetpp::simtime_t creationTime = SIMTIME_ZERO;
    long priority = 0;

  private:
    void copy(const MoqTrackHeader& other);

  protected:
    bool operator==(const MoqTrackHeader&) = delete;

  public:
    MoqTrackHeader();
    MoqTrackHeader(const MoqTrackHeader& other);
    virtual ~MoqTrackHeader();
    MoqTrackHeader& operator=(const MoqTrackHeader& other);
    virtual MoqTrackHeader *dup() const override {return new MoqTrackHeader(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual long getTrackId() const;
    virtual void setTrackId(long trackId);

    virtual const char * getTrackName() const;
    virtual void setTrackName(const char * trackName);

    virtual long getObjectId() const;
    virtual void setObjectId(long objectId);

    virtual long getPayloadSize() const;
    virtual void setPayloadSize(long payloadSize);

    virtual ::omnetpp::simtime_t getSendInterval() const;
    virtual void setSendInterval(::omnetpp::simtime_t sendInterval);

    virtual ::omnetpp::simtime_t getCreationTime() const;
    virtual void setCreationTime(::omnetpp::simtime_t creationTime);

    virtual long getPriority() const;
    virtual void setPriority(long priority);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MoqTrackHeader& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MoqTrackHeader& obj) {obj.parsimUnpack(b);}


}  // namespace moqveinssim


namespace omnetpp {

template<> inline moqveinssim::MoqTrackHeader *fromAnyPtr(any_ptr ptr) { return check_and_cast<moqveinssim::MoqTrackHeader*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __MOQVEINSSIM_MOQTRACKHEADER_M_H

